services:
  fastapi:
    build:
      context: ./FastAPI
      dockerfile: Dockerfile
    env_file:
      - ./envs/FastAPI.env
    ports:
      - "${FAST_API_PORT}:${FAST_API_PORT}"
    volumes:
      - FastAPI_log:/FastAPI/log
    networks:
      - app_network

  # CeleryWorker:
  #   build:
  #     context: ./FastAPI
  #     dockerfile: Dockerfile
  #   command: celery -A celery_app.celery_app worker --loglevel info --pool=solo
  #   networks:
  #     - app_network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - ./envs/backend.env
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    networks:
      - app_network
      - nginx_net

volumes:
  FastAPI_log:

networks:
  app_network:
    name: app_network
    driver: bridge
  nginx_net:
    name: nginx_net
    driver: bridge
