version: 1
disable_existing_loggers: false # 기존 로거를 유지

formatters:
  default:
    "()": uvicorn.logging.DefaultFormatter
    use_colors: true
    fmt: "[%(thread)s]\t%(levelname)s\t%(asctime)s | %(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"
  color:
    "()": config.custom_formatter.CustomColorFormatter
    fmt: "[%(thread)s]\t%(levelname)s\t%(asctime)s | %(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"
  plain:
    "()": config.custom_formatter.PlainFormatter
    format: "[%(thread)s]\t%(levelname)s\t%(asctime)s | %(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"

handlers:
  console:
    class: logging.StreamHandler
    formatter: color
    stream: ext://sys.stdout
  file:
    class: logging.handlers.RotatingFileHandler
    formatter: plain
    filename: log/uvicorn.log
    maxBytes: 10485760
    backupCount: 5

root:
  level: INFO
  handlers: [console, file]

loggers:
  uvicorn:
    level: INFO
  uvicorn.error:
    level: INFO
  uvicorn.access:
    level: INFO
